### ISSUE TITLE
Issue at deleting product

### ISSUE THREAD

**Issue by alfredrafael** [flaviocopes/react-ecommerce#1]
When deleting a product, a `cannot read property 'image' of undefined` appears. Find image attached: 

![screen shot 2019-01-31 at 9 25 52 pm](https://user-images.githubusercontent.com/30055877/52099070-91f08e80-259f-11e9-894e-37eb094135e5.png)

**Comment by flaviocopes** [comment]
Right! The onClick event handler had to call stopPropagation() otherwise the outer onClick handler (that manages the list item click) kicked in.
Fixed in https://github.com/flaviocopes/react-ecommerce/commit/8e8a09d7ab8b82bb8b4cd5bb66ce6c811e718c66
